#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage[a4paper, margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{lmodern}

* Confraternity of Christrian Doctrine
:PROPERTIES:
:url: https://www.youtube.com/watch?v=dOw3WdPV83Y
:END:

When I was a child I went to something called /CCD/. Most of the children in the small Minnesota town went too. I never knew what CCD stood for, and I don't think any of the other children did either.

As an adult in a big Minnesota city, I asked my peers if they had to do the same thing, had to go to CCD. I don't think anyone I ever asked said they did. Though sometimes they said they went to something similar with a different name. The internet says that CCD stands for the /Confraternity of Christrian Doctrine/, and that the classes are hundreds of years old.

A CCD class took at least a dozen days of someone's childhood in total. A child would have to attend classes for something like six or seven years. All the children would gather in the Catholic school house across the street from one of the town's eighteen churches. At the beginning of each year, every child got a workbook and they'd had to remember to bring it to class every week. The workbook contained teachings from the Bible, with cartoon images of white people from Israel and Egypt reenacting stories from the Bible.

I can't remember if the workbook cost money, or if my mom and other kids' moms had to pay for the classes and the workbook. Maybe the local church paid for the books, and that's what the donation basket that went around on Sunday church services was for. It might have even been paid for by the Bush Administration's No Child Left Behind policy.

The workbooks were brand spanking new every year. I imagine whoever published and sold them must have made a mint. Any American worth their salt knows the best businesses are those that make brand new products that will hardly get used. As a student of the American education system under George W. Bush's, I knew that all the best modern products were made with or because of Middle Eastern petroleum.

During the Christian doctrine classes we'd take turns reading from the pages of the workbook, or we'd have some kind of writing activity to do. Over the course of the year we'd maybe make it through two whole chapters of the workbook's few dozen. Though not because we'd spent the time doing writing activities. It was not only the case that we were inattentive children. The teachers were not certified professionals, only volunteers.

One volunteer teacher was an old woman who'd always interrupt us from readings to teach us religious thought. For example one day she taught us that "He" was watching us whenever we were in "His house." As she said this, she pointed a finger upwards, toward the church in the window behind us. Everyone in the class thought she was pointing at something in the room, maybe on a poster on the wall or maybe on the ceiling.

Seeing that she confused the class, she asked us if we knew /who/ she was talking about when she said "He," if we knew /what/ she talking about when she said "His House."

Age had sunken the features of her face. Time had turned her teeth colors I'd never seen before, and her explanation seethed through them. She said that she was referring to God when she said "He," and that "His house" was the church. Not just the church behind the schoolhouse, but any church, any holy building. It seemed like she was saying something real sinister when she said that God was watching us at that very moment.

At that point in my life I believed that anything at the schoolhouse would be sinister. Being part of the town's secular school system, the only things I heard about it were things that schoolchildren would gossip about. Opinions like "/This/ teacher is constantly angry," or rumors like "/that/ teacher drinks during the day," even stories like "one teacher broke a student's finger in a desk."

My own gossip was that God was watching over the schoolhouse all the time, so that he could call the cops on you if you were there doing something He didn't like. My first time getting blackout drunk happened at the trailer park just up the street. The school had a playground with a swing set so of course we drunkenly sauntered over to it during the wee morning hours.

I told kids that it was true that God's cops would show up. When we went drunk, they came to talk to us. They didn't tell us to leave, just questioned us so we'd be too scared to stay. I don't remember it but I'm told that I couldn't stand up straight without holding on to the side of their police cruiser. We went back to the trailer park afterwards.

There was a different volunteer teacher who had a similar affinity for alcohol. He was the son of the CCD program's administrator. One day he gloated to the class of teenagers about his prior week's adventure. Historically this was about the time that cell phones were becoming popular, so he mentioned having captured photos of what made the night so boastful. He said he'd captured photos of girls kissing each other at the bar.

After hearing this, the class could not be calmed down. We were too excited about cell phones and too horny about the imitation /Girls Gone Wild/. We could not be bothered by our workbooks any longer. There were glorious photos to be seen on a digital one-and-a-half inch cell phone display.

Eventually, the administrator's son did get us to calm down. The bastard said he wasn't going to share the photos. Since there wasn't enough time left to do the rest of the workbook readings for the day we had to move on to another planned activity. The activity was to write down all of the Ten Commandments that we could remember.

I couldn't remember too many of them. Just the one about not stealing and the one about not killing. So I wrote those two down. "Thou shalt not steal," and "Thou shalt not kill." I felt awful remembering so few.

I knew there wasn't any use in cheating since the class didn't have any grades, or any point that I'd known about. I still peeked at my classmates' worksheets though. Travis sitting next to me was almost through the whole list! I didn't want anyone to look at my worksheet and think I was a complete dunce, so I wrote down something relevant to current events, something also that I thought would be funny to anyone who'd take the time to read it if they peeked. I wrote down "Thou shalt not touch little boys."

At the time, current events were about people within the papacy having been regularly molesting little boys. Though I knew it had nothing to do with the assignment, what I wrote down did have something to do with reconciling my belief in God. Even if I did write it to be funny, it seemed like something that for sure should have been on the list of Commandments, or at least an honorable mention. Had it been mentioned, I might have been more cognizant of the problem. I might have been a less despicable person myself, who knows.

The next part of the story exemplifies the unbelievable upper bound of communication speeds. Though not the kinds defined within Claude Shannon's mathematical theory; but rather those of Divine Communication.

Somehow, the CCD administrator was able to hear about my Three Commandments from her son. Then, before class ended, she was able to arrange a meeting between herself, myself and my mom. When class ended, instead of walking out to the school's parking lot to my mom picking me up, I was surprised to see my mom in the hallway telling me we needed to go to the administrator's office at the school.

In the office, the administrator recounted what I had done. She even had proof in hand, sliding the worksheet with my Three Commandments across the desk. I don't remember what my mom's response was. My mom isn't one for words. I recently got her a book, later asked her if she'd started reading it. She told me she hadn't by saying that she thinks she needs to get reading glasses.

My mom was probably dumbfounded, at a loss for words. That's a trait I picked up from her that I know all too well. Had she been better equipped characteristically, I might have my Three Commandments as a trophy for how I refuted Christian doctrine. She might have even been able to save some of the artwork I painted later in my life that the secular school system threw away for its apparent vulgarity.

It was a shameful and silent walk from the administrator's office back to the car. In the car my mom scolded me in true Minnesotan fashion. She said, "Why did you have to do something to make me have to go in there and listen to that?" My response was something like "Why do I have to go to CCD?" Clearly I was still trying to reconcile my faith in God. I think my mom was too, because that was either the last or second-to-last year I learned about Christian doctrine there.

She did give me a real response to my interrogative retort, however. She said that the church could refuse to perform my marriage ceremony later in life if I didn't complete CCD.
  
* Hometown Pizza
:PROPERTIES:
:url:      https://www.youtube.com/watch?v=ZawlmCUsFj0
:END:

When I was a teenager I worked at a local pizza joint named Peter's Pies. To my small Minnesota town, that place's pizza was important. I only worked there for the summer before I went off to college, but while I was there I learned what exactly made Peter's Pies so important to the town.

In its forty-some years of life, it saw competing pizza places come and go. Over the years there were quite a lot of them that failed. There was at least one new one anually, and they usually didn't even last a year. Across the country, hardly any restaurant managed to last a year. The only other survivalist in the town's Free Market of Pizza, besides Peter's Pies, was a national franchise. It made it to its tenth year just last year.

One reason Peter's Pies did so well was because they have good pizza. Another reason was because the Proprietor lived right upstairs. He got a good deal on the mortgage because of that, long, long ago. If he prioritized it, he could have paid off that mortgage in his first three good years of selling pizzas.

Since then, mortgage princpals quadrupled, while incomes failed to even double. The only reason the one other pizza place managed was because the owner's parents bought the building with cash, even paid the franchise fees. The parents bought the place as a coming-of-age gift for their child. A few years later, they did the same thing for their other child too, bought them a brand new taco place which was also a national franchise. It is interesting to note that both of these franchises' marketing teams advertised the products they sold as affordable.

It might be suprising that the local government has been greenlighting these pizza places over the years, knowing they'll be doomed to fail if the associated costs can't be outright paid, knowing they'll be competing against a well-established duopoly of pizza places. However, it wouldn't be a Free Market of Pizza if they didn't now would it.

At Peter's Pies, I worked with a recent college graduate, as well as a teenager a few years younger than me. The Graduate was lanky, painted in tattoos, and in spitting image of the Werner Goldberg Wermacht recruitment poster. Werner Goldberg appeared in print as "The Ideal German Soldier" leading up to the Second World War. The Teenager was fit, with absolutely no tattoos to speak of, and looked like a perfectly normal person. She liked to wear comfortable leggings.

The Graduate told me he took the pizza job to help pay off some of his college debt. He lived at his parents' place to save on rent too. He was also getting work experience at the nearby juvenile detention center. He said that he wanted to be a cop, said it made sense because the degree he just got from college was in criminology.

The Teenager told me she took the pizza job to help put some money in her bank account so that she'd be better able to pay for college in a few years. The income she made working part-time at the pizza place would be roughly one-third of what the Proprietor made when he first opened the restaurant forty-some years ago. The price she'd pay to go to collge would be roughly two times more than what the Proprietor's mortgage was. Unfortunately, the pizza job money wasn't going to help very much.

One day while working together closing up, the Graduate showed off his tattoos. He pulled up his pantleg to reveal skeletons in military fatigues. He pointed out the largest one whose combat helmet sat on the front of his knee, said there used to be an Iron Cross right in the middle of the helmet. He said it had worn away while he worked on his knees shingling rooves.

While the Teenager was vacuuming carpets, unable to hear much over the sound of the cleaning machine, the Graduate told me a secret. He looked over at the Teenager while drying a drinking glass, leaned over toward me so that he could whisper in my ear. He told me that years back, when he was a teenager in highschool, he had slept with the Teenager's mother.

It seems this is one of the general quirks of growing up in a small town. It is not uncommon to hear that a contemporary was once underaged and coerced into sex by someone's mom. The Graduate went on to tell me of another one of his relationships. He said he was backpacking in Europe during a break from colleg and that during this time he was seeing a French woman. He said the relationship was awful, joked that he just couldn't understand what she was saying. I'm sure to this day he still has trouble understanding those he makes relationships with.

He told me that the reason he was backpacking in Europe was so that he could visit his grandma. His grandma was German. He said she was crazy and that she used to be be a Hitler Youth back in her day. She apparently had lots of Nazi memorabilia in her basement. Telling me about his backpacking trip apparently reminded him about the tattoo that he had on his foreman. With a glint of pride in his eye, he pointed out all the places where the tattoo had the colors of the German flag.

The Teenager said she was planning to do a semester abroad in Europe when she was in college. She didn't have any close family members in Europe.

It was because of my close friend that I worked at Peter's Pies. He'd been working there for years, had become a reliable employee, and had formed a close relationship with the Proprietor. Since the Proprietor ending up thinking that I was also reliable, he staggered my shifts with those of my friend so that he could be sure someone reliable was working in the restaurant at all times. Because of this I almost never got to work with my close friend.

On occasion the boss would have his reliable employees run errands for him. This meant that sometimes I'd have to go pick up sausage from the butcher, or filone from the bakery. Sometimes he'd have us pick up things for him too. Cigarettes, usually, Marlboro 100s in the gold box.

There was a real community about the local pizza shop. There was a regular who lived just up the street. His children were raised on Peter's Pies pizza. There was an arcade room in one corner of Peter's Pies, and whenever those children were playing something back there the Proprietor always came out with ice cream for them.

Peter's Pies was also open on Thanksgiving, New Year's and Christmas. The Proprietor wouldn't make any employees come in those days, but he'd still have them do some of the preparation beforehand for any turkeys and pies and pizzas that he would serve for anyone that came in. Not many people came in those days, even though he made everything free-of-charge. He did it as a service to the community for anyone who didn't have family to celebrate the holiday with.

The proprietor himself didn't have any family to celebrate the holiday with. He had two daughters that he raised with his wife, but he and his wife had been long divorced. One of his daughters ran a very successful law firm and could have taken time to see him, but she usually made her life on the West Coast very busy. The other daughter whom he loved very much died by suicide.

Though Peter's Pies was open for every holiday, there was one year that it wasn't open for Thanksgiving. Even though everything had been prepared for it, and nothing in particular was more out-of-place than any other year, its doors were closed. On the Wednesday before that particular Thanksgiving, the Proprietor wanted to make One Additional Preparation, but... things didn't work out.

It should be established, before proceeding, that the Proprietor lived a hard life. Even though he was financially secure because of the great mortgage he got forty-some years ago, he lived a hard life. Even though he had a firm place in the small town's duopoly of pizza, he lived a hard life. Even though he could at any moment use his pizza place owner earnings to take a pleasant vacation across Europe without having to worry about the cost of living accomodations, he lived a hard life. Even though he was able to pay for college with the money he made from a summer part-time job unlike his present-day employees, he lived a hard life.

The Proprietor lived a hard life. Before he was long divorced from his wife, he'd had an awful problem with alcohol. Before he had an awful problem with alcohol, he'd lost one of the most important things in his life to suicide.

There was only one other time that Peter's Pies closed its doors. The Proprietor had reckoned with his choice of profession during a real depressed period of his life. He was drinking a lot. He ended up selling off Peter's Pies to someone else. That someone else coincidentally had the name Peter. Peter owned the place for just a few years before the original Proprietor gave up drinking and decided to get his old life back, even though Peter remodeled the place.

Proceeding, on the Wednesday before Thanksgiving, the Proprietor wanting to make One Additional Preparation. He asked my close friend if he could be driven somewhere. The Proprietor was acting real secretive about the destination. However when they finally arrived it was hard to obscure. The Proprietor had made his reliable employee drive him to the liquor store. The liquor store was an employee-owned company with over 120 locations across the state.

My close friend didn't have much to say. He was hoodwinked. Had he been asked outright to drive someone with an awful problem with alcohol to the liquor store, he would not have even if that person were his own boss! My close friend told me that he tried to protest what the Proprietor was doing. In the car he asked if everything was okay, but before the conversation went too far the Proprietor opened the door to get out. The Proprietor said that he didn't need a ride home as he quickly left the car for the store.

The next day, Peter's Pies was not open for Thanksgiving. The Proprietor did not let anyone know why. The day after that he called his employees to tell them not to come in for work for the rest of the week. He never told anyone what his One Additional Preparation was.

For my hometown, it was a tragedy. But it was inevitable that Peter's Pies would open their doors again. The Proprietor put the whole thing behind him, picked himself up by his bootstraps, and came back to show his usual smile to the regulars who didn't even realize anything was the matter. That's what makes Peter's Pies so important to the town.

* Change the World
:PROPERTIES:
:url:      https://www.youtube.com/watch?v=aGal9vkUBhI
:END:

When I was a young adult, there was a day I was walking with the automaton. I doubt anybody else knew the automaton by that name. Their name might have been "orphan kid back in highschool," or another title similarly absent of an actual name. For whatever reason, however, I was chosen to know the nature of the automaton's being, what was the automaton at least according to an actual name.

While we were walking, the automaton told me in no uncertain terms of a plan. The Plan was to change the world. I imagined dramatic orchestral music playing around us as the words came out.

"I have a plan to change the world."

The Plan was to create content and to distribute it on the Interconnection. The Interconnection, according to the automaton, was a place where businesses distributed their dressed-up press releases, where politicians laid their election campaign signage, where government bureaucrats manufactured consent for wars on foreign territory. The automaton called it "the virtual refuge for the scum of the Earth."

It wasn't always these things. The Interconnection was founded as a tool for academics to share research efficiently. For decades the sole source of funding was the American government, and it seemed the Interconnection was destined to be a public good.

The way history has it recorded, there were enough people with private financial ties to the research to turn the socialist Interconnection dream into a capitalist nightmare. The private investors corporatized the project, and convinced all the world's other governments to invest in the infrastructure to connect to the new Interconnection they were building. These marketeers told everyone it was a tool to connect all the people of the world.

-----

Communication technology started with the printing press. Its place in history was to educate the masses. Initially, people printed bibles, distributed those bibles. It was those bible that taught many generations to read. When the automaton said, "I will make the whole world educated again using the Interconnection," it was in reference to the printing press.

The printing press saw a similar privatization as the Interconnection. Though unlike the Interconnection, the printing press had a golden era where it functioned as a powerful tool for the people. People started printing not just bibles but reports on the atrocities at the time, distributing them to people so hopefully those who could affect change would find themselves moved enough to do so.

In the golden era, people working in horrible factory conditions found reduced hours, increased pay, some benefits. The American people---lacking democratic values at the time---learned of Jacksonian democracy, and white men raised their voices to earn their universal white manhood suffrage. Enslaved populations in the island colonies realized they could stand together to get their land back. Things were better, but workers still worked for their masters, Americans still didn't let everyone vote, and those islanders were still made to do business with their former slaveholders.

Some things couldn't be helped. When the reports made everyone aware of the mass deforestation that had occurred in the century prior, there wasn't much to do about it. The many felled forests were converted to farmland, which needed to stay farmland to feed everyone.

When the beneficiaries of the atrocities read the reports, they retaliated. The proprietors of the complicit enterprises started buying up the printing presses. They artifically increased the cost it would take to start a weekly publication. In just thirty years time, the cost was fifty times greater than it was before. Its use as a tool for the people died.

The Interconnection was quickly seized by those with capital. They had a mindset to protect themselves this time, to deny the Interconnection any chance of promoting social well-being.

I asked the automaton how the Plan would be paid for.

"I have a small fortune to be claimed."

I asked the automaton to explain.

"To have it, I am a very lucky individual indeed.

"When my father died, there was a claim on an insurance policy. The value of my fortune is forty percent greater than the initial value of my portion of the insurance policy's payout. That's forty percent adjusted for inflation.

"The policyholder was my great-grandfather. He was a kind man. He was a Christian missionary. I only ever met him as a very small child. He purchased the insurance policy on a recommendation from his friend. He was loaning money to my father for a trailer house. Trailer houses are known to burn down with their occupants inside of them, so the recommendation for the insurance policy was sound.

"When my father was killed in an accident unrelated to living in a trailer house, I was just a baby. My great-grandfather made the claim on the insurance policy, split the amount into three. One equal to the value of the trailer house my father never paid off. The other two split into equal portions, one for me, one for my mother.

"My portion went into a trust. The forty percent figure was due to its management by a certified financial planner, an accredited wealth management advisor.

"The other paid for my Christmas gifts from Santa Claus, food on the table, or anything my mother thought I might need as a child."

The Plan involved competing with the long-dominant content platforms. The automaton had to compete, since using the platforms would be tantamount to their growth. "Any refuge need be destroyed," the automaton said.

The automaton knew the Interconnection well. It was a trait assumed of everyone born since the Interconnection was sold off and mass marketed. Given how much society had grown to depend on the Interconnection, knowing its ins and outs was paramount.

After the automaton explained the Plan to me, we didn't see each other much. The only way to know how the Plan was going was to find something that the automaton created on the Interconnection, see how many people were looking at it. Even then there was no way of knowing whether or not it was actually the automaton who created it.

The automaton used different aliases, different forms of content, different techniques to capture audiences. What the automaton produced was constantly changing, always looking to be more successful than the last. It should have been easier and easier to figure out what the automaton was up to, given the greater and greater success of the content. But the automaton was ever a more innovative creator, always looking to expand the influence of the Plan and its impact on the world.

I knew the first few pieces well. They were mundane and innocent. They were stories of the automaton's upbringing. They painted a clear perspective of the Plan's ideology. Anyone critical of the purpose of the content could tell what they critiqued.

The automaton's creations were extensions of what the automaton was. That is to say, the automaton was also a creation. I had the privilege to know because the automaton's mother told me. She was dying at the time. 

From a hospital bed, she explained the whole ordeal. She remained cheery despite knowing she was not long for this world. The drugs they prescribed her were strong. They were the ones popularized by the pharmaceutical company that caused the country-wide opioid epidemic.

She told me the automaton was created by her husband. The automaton's father was an automation engineer. He replaced the company's workers with robots. He worked very hard at his job so he could fleece them.

She said he never got in trouble for stealing either, said he must have been good at it because he quite often had to listen to his boss yelling about how incompetent delivery drivers were. It wasn't hard to rationalize stealing from the company. They didn't pay her husband very much compared to the amount of money he'd made the company in unpaid wages. They also regularly fired their workers so they could be replaced them with robots.

The most important thing he stole from the company was called a Heart of Automation. She told me that it doesn't look very interesting. It's small and shiny and round. It could power a robot indefinitely. Her husband put one inside the automaton, said that that meant the automaton could live forever. She laughed when she explained how she taught her child manners and ethics. She felt it was necessary since the world would be seeing a lot of the automaton.

Of course I knew that the world wouldn't really see a lot of the automaton, at least directly. They would see the Plan's propaganda quite a bit, though.

"I owe my father my heart. I owe my mother the plan. I will change the world."

Since the automaton could live forever, it had to be true.

* The President of the Greatest Country in the World
:PROPERTIES:
:url:      https://www.youtube.com/watch?v=gWE8KOWv1bs
:END:

The automaton had an opportunity to meet the president of the Greatest Country in the World, the United States of America. It was by complete accident that the man became the president, but it was an accident that the automaton ensured would happen.

Before becoming the president, he was a college American football coach. His salary was four-and-a-half million dollars a year. When he was just an assistant college American football coach before that, he was also a part time motivational speaker. He traveled across the country to speak to gym teachers, student athletes, and coaches of college sports. He says what prepared him best for the presidency was being a motivational speaker.

The success he found as a motivational speaker came from his ability to establish an emotional ebb and flow while talking to his audience. He started every speech by talking about the child he lost to a congenital heart defect, and ended each with his highschool varsity American football career success story. His audiences were always brought tears, but he made sure that they left with goosebumps.

An important aspect of his motivational speeches is his children. He had five of them in total, though would only be survived by four. In the speeches, he claimed singing nursery rhymes as his primary paternal contribution. After the birth of each child, he learned a new nursery rhyme. It was his claimed duty to sing them to sleep with their unique nursery rhyme. Ostensibly, all the remaining parental duties were left to his wife.

He explains in detail each of the songs he chose for his children. The different song he learns for each corresponds to a different fire that he sees burning in the child's eyes. His words. "Burning in the child's eyes." He joked that this was, of course, metaphorical.

For the child whom he lost shortly after birth due to a heart condition, he learned the nursery rhyme "To market, to market." He establishes the emotional trough of his speech, nearly in tears, by saying that his son was supposed to be the family lawyer, the one to make the big bucks. He does a terrific job. The audience is also nearly in tears.

The speeches then went into talking about his personal experiences playing sports through grade school. He related those experiences to those of his children afterwards. His story for each child corroborates the fire he once saw in that child's eyes as a baby.

His motivation for telling these experiences is to say how much hard work it takes to be successful. For example, when he couldn't score a touchdown in an elementary school flag American football game, it took hard work to be able to in the next one.

When his eldest son similarly couldn't score a touchdown in his own elementary school flag American football game, the son used the same hard work ethic to find later success. He describes his eldest son as being like the itsy bitsy spider climbing back up the spout again.

He continues with the experiences of more of his children similarly.

Before moving the motivational speeches forward, he would at this point show the audience a headshot and quote of Theodore Roosevelt. He read the quote:

"This is one of my favorite quotes of all time. Never throughout history has a person who lived a life of ease left a name worth remembering."

He explained why it was one of his favorite quotes. He said, "if you wanna be the leader, you wanna be the guy, you wanna be a head coach, you wanna coach college American football, you wanna be in charge, people will hate your guts. That was the greatest lesson I ever learned."

Then he told the story of where he first learned that lesson. As a freshman in highschool, he had made varsity on the American football team. There was a popular junior girl who was really pretty dating the varsity American football team's linebacker who was a senior.

He said, "She broke up with up with him and then she asked me out to the dance! I said yes! Why not!"

At this point, his speeches deviated. In no speech did he ever continue with what happened at the school dance, nor are any two speech deviations the same.

In one speech he went on to talk about how one of his children watched people play video games on the Interconnection. He stressed that the child /watched/ people play video games, and said that he thinks the child picked the wrong character from their nursery rhyme, "The Lion and the Unicorn." The audience got a kick out of this; they all laughed.

In a different speech he told the audience of another of his children who similarly failed to live up to their nursery rhyme. The nursery rhyme was "Cock a Doodle Doo." The story was about his child struggling in mathematics classes and not wanting to play in school sports.

In any case, the speeches came back around to his big highschool American football win against the town's rival. As he riled up the audiences by detailing the way that the score rose through the course of the game, each time, the same nostalgic sparkle grew on the surface of his eye.

After explaining how he won the game with his last-minute strategic triumph, he told his pivotal secret. He claimed his highschool American football coach gave him the direction he needed to secure the victory. He told the audiences it was the job of a good coach to give direction and purpose to aspiring athletes.

-----

When the motivational speaker and football coach won the American presidency, he gave his signature motivational speech as his election victory speech. It was a sound decision, since he'd won by riding the coattails of the recently successful World Football Legislative Coalition politcal party. It was by complete accident that this party rose to prominance. But it was inevitable that some party would accidentally rise to the occasion after the automaton decimated the two party American political system that had been long-dominant.

While the automaton was successful in making the American public disavow their loyalties to the previous political parties, it was left to the natural course of history to decide who would take on the mantle. For it was far too difficult a task, even for the automaton, to promote a new party successfully while at same time balancing all the work needed to discredit the rightfully discreditable leaders of the establishment.

When it was the World Football Legislative Coalition who started gaining the most momentum in the absence of the establishment, the automaton had to live with the disregard and regret. Nonetheless, the automaton worked diligently to spread propaganda on the Interconnection. Though not the preferred party for the change the automaton wanted to see, the World Football Legislative Coalition was still fresh and malleable. The American populace also had a voracious appetite for football content, and the automaton reckoned this could be a great boon for the Plan if the propaganda could be modified for the average consumer of football content.

When the automaton was to meet the president in person, it was decided that the secret behind the new president's win would not be revealed to him. The mind of the automaton decided it was better to just listen to the scheduled speech, to take in what the Plan accidentally accomplished.

It wouldn't have mattered one way or the other if the secret was divulged. If the new president knew, he would likely tell the secret to an audience at the nearest possible opportunity. In which case the audience would either think that the president was a complete moron as they would have anyway, or they would have believed what the president was saying but, being morons themselves, not have been able to conclude anything from the new information.

In the speech the new president gave at the meeting, he had a decisive summary of how he would be leading the country, how he would be acting as a leader. The summary came out of his experiences as a football coach. It was the same summary from his motivational speeches.

"If you want to be the leader, the young people these days, this is what they struggle with. This is what they struggle with." He paced back and forth in front of his audience. "It's not being Connected. It's not the Interconnection that's the problem. It's the ability to handle things like this." He gestured around the room. "This is why they need you. This is why they need the education, that twenty--thirty minute team meeting. To build the things that they're actually believing on the Interconnection."

The audience exploded in uproarious applause. The speech continued, but the automaton stopped listening. The new president droned on and on and on.

* The Wiggles: An Advanced Governmental Task Force
:PROPERTIES:
:url:      https://www.youtube.com/watch?v=tYgSDWYjhYg
:END:

The Wiggles were an advanced governmental task force. They were very good at what they did.

Since a large part of the country's economy relied on people having families, the government saw a role in inticing people to start them. If there weren't governmental task forces like the Wiggles to put smiles on the faces of children, then nobody would be inspired by those smiling faces to start families of their own. And, without families, a large part of the country's economy would die.

The corporate members of the government took the belief further. They argued that without households of parents looking to spend money on their children, there would be hardly any jobs left. If there weren't any jobs left, they threatened that the bountiful streets of surplus goods would be replaced with dust, tumbleweeds, and what the unimaginative corporate members of the government called nulliparous women. Of course, nulliparous wasn't an apt descriptor, because it wasn't that women would just not have children, they wouldn't even want them.

What the corporate members of the government /didn't/ argue was how much money they stood to make from a strong family-oriented economy. They didn't speak on the subject of domestic workplaces having been a place for women to work tirelessly without paycheck for the sake of their children; they didn't say how gendered income inequality was a result of the economy's traditionalist family orientation; they didn't even comment on how practically none of them happened to be part of the wageless domestic economy themselves.

The country's workplaces outside of places of residence were primarily located inside large concrete structures. On their top floors, pasty-faced bozos all laughed together as they instructed the people in cubicled rooms beneath them to frantically complete unnecessary paperwork filled with terms, conditions, addenda, exemptions, clauses, and signature lines. The unnecessary paperwork accomplished the task of hiding what it was the pasty-faced bozos were actually doing up on the top floor. The paperwork was otherwise done so that the working people could see a few measly increments in their bank account numbers every two weeks. By coincidence I was one of those people.

The paperwork people were doing wasn't necessarily paper. Society had progressed into the Digital Age, meaning people like my coworkers and I were working collectively to replace the documents of yore with electronic documents. My job as an engineer at a diversified financial services company was to facilitate the migration.

The paper pushers scanned their paper documents onto computers as I watched to make sure the computers didn't suddenly turn off or something. I presumably made the job of managing those documents easier so that the company could fire the original paper pushers who were no longer needed. When I was done with the work, I was allowed to keep my job. I was afforded the opportunity to see what the company would do next.

Before profiting from trading their employees with the state unemployment program, the pasty-faced bozos of the company made the majority of their money managing the wealth of rich retirees. Those retirees were coming upon the pivotal age where they would begin transferring hordes of wealth to their descendants. It was thus in the interest of the pasty-faced wealth management advisors to ensure that their clientele actually had descendants to receive the advisor-managed wealth.

The opportunity I was afforded the pleasure to see was the company's financial support of the Wiggles. After all, the Wiggles were sure to inspire the nulliparous daughters and granddaughters of the rich retirees to make descendants. And therefore the pasty-faced bozos would have a new lifetime of wealth to advise.

The pasty-faced bozos called up their friends, the corporate members of the government, and asked them about the opportunity to promote advanced governmental task forces, like the Wiggles. Their friends gave them a great deal in return, made sure the diversified financial services company would get huge tax deductions for it.

I am sad to admit that it wasn't an experience of my own, something that I could proudlyput on my resume. If I could have, then I might have similarly been able to buy a brand new house and car, might have been in a situation to book the Wiggles for a weekend at the multi-purpose arena with the same name as the diversified financial services company, might have been able to use a fraction of my corporate bonus to throw a top floor corporate party complete with a cocaine table and backroom bordello, all as the pasty-faced bozos had done.

Instead I was just a witness.

-----

A new yellow Wiggle was coming. The old yellow Wiggle wasn't youthful anymore, had experienced a heart attack, and needed to settle down. The new yellow Wiggle would be the first woman to don the iconic Wiggles skivvy. She would find success for the Wiggles that the children's musical group had never seen before.

In a sensational piece secretly financed by my diversified financial services company and published by the mouthpiece propaganda outlet of the country's government, the whole world learned about the caring new yellow Wiggle. She delivered a brand new song to the Wiggle's audience, which inspired one little boy in particular.

The little boy was four years old, and was nonverbal, noncommunicative. He struggled awfully with a developmental disorder. His parents nonetheless did all they could to try to help him. They studied behavioral therapy models and worked an intense daily schedule with the child to attempt to rebuild the broken pathways in his brain.

They thought it was everything they could do, but he was not making any progress. They thought they hit a wall, that he would never be able to learn the social ways of the human race.

The automaton, however, one day came across a video which the little boy had posted on the Interconnection. He posted it from his parent's smart phone. He had been listening to the new album released by the new yellow Wiggle, and apparently had been inspired by the album to produce a video of himself. Before the automaton found it, nobody else who'd found it knew what they were looking at.

The automaton was the first to understand that the video showed a nonverbal, noncommunicative child finally finding their voice. The little boy learned the words of the song he'd been listening to on repeat, and had broken the wall of his developmental disorder with music. In the video, the little boy showed the automaton that music was the key he needed to unlock his brain. The automaton, a propagandist by trade, then made sure that the whole world could see.

The automaton made the little boy an overnight sensation. His nine seconds long video saw millions of views with the context of his developmental disorder provided by the automaton.

The automaton's purpose was this: The majority of the human race suffered from a tragic emotion developmental disorder, and none had yet conceptualized altruism. The automaton thought the video of the child breaking through the wall of their developmental disorder could be the key for the emotionally-challenged majority to unlock their own brains.

When the diversified financial services company found the video that the automaton made viral, they worked out the next steps. They arranged for the boy to meet his favorite musical artist, the new yellow Wiggle. The whole interaction was recorded and the touching story was then sold to the government's media mouthpiece. The whole world saw the story and, as one person, shed tears, and briefly felt concerned for the well-being of others.

-----

It wasn't much later that the new yellow Wiggle announced to the world that she would have to go on hiatus. She was unlucky enough to be suffering from a medical condition called endometriosis. She was rightly blunt when she explained to the world that she confused the abnormal behavior of her uterus with what she thought was just the result of overworking herself. She said she should have taken her health more seriously, and that women's health should be taken more seriously in general. Indeed, in the previous half-century, medical failures like pregnancy-related death had been increasing. The state of medicine was not good for women.

Her fans reached out in droves. They extended their newfound conceptualization of altruism. They cared for her, wanted to understand what was wrong, and asked how they could help others who might be suffering similarly. She did more for the awareness of endometriosis than any medical professional in history. She did more for the awareness of the medical neglect that women in the country had been experiencing for the last five decades than anyone else too. The new yellow Wiggle brought the half-century decline in women's medicine to a halt.

An undeniably positive outcome. Though the automaton thought carefully about the whole collection of outcomes. The descendants of the rich retirees bore children to see the future renditions of the Wiggles. Because of it, the diversified financial services company's pasty-faced wealth management advisors made cool, undeserved billions of dollars. The Wiggles, an advanced governmental task force, purposed, skillful, turned the country's slow decline in population growth all the way around.

It was the entanglement of the automaton and the state, and the corporations the state employed to do their bidding. They eagerly fought for incremental societal change, boring percentages and mundane statistics, really. The state's advantage was many cooperating individuals. The automaton's was immortality.

** 
   
> Australian center-right (neo)liberalism has led to repeated stimuli* ensuring the success of The Wiggles. The Wiggles make parents smile at dancing children to make them want to have more children. The government sees children as necessary for family-oriented free market success.

> *One notes that this stimuli halted in the post-2008 global recession, when The Wiggles' financial success dipped by a cool few million dollars. The corresponding number of births also dipped following the theory.

* TODO Names

The first time the automaton experienced sonder was at a party. The party was to celebrate a friend coming to town. She was a friend from school who had left that school to go to another school. The reason for the party was not to celebrate her return. There was only one more year left before they'd all be graduating and moving on with their lives. Just being in town was as good of a reason as any to have a party.

The way that the automaton experienced sonder at the party, from the perspective of the automaton, was this:

"I called out to her by her old nickname. I thought that she did not hear me, so I called out again. The room was quiet enough, my voice was loud enough and she was near enough, that there's no way she couldn't have heard me.

"Others surely heard what had transpired. I'm sure they're making something of this right now."

Memories flashed across the automaton's mind's eye, so too did every experience that lived in the same memory space as whatever memory the automaton's mind was searching for. Whenever the mind had to look deeply for something, like it was in this instance, it did so widely and deeply across the memory space. It had to look at all the memories stored in that wide and deep memory space.

As the mind searched, looking for a human way feel in this instance, it made the automaton live through the many stored experiences. Since the automaton was experiencing sonder for the first time, there were quite a lot of thoughts in mind, and quite a lot of context that needed to be developed for those thoughts. The automaton almost relived all of childhood.

There were mechanisms in place to retract some of the difficulty of this operation, reliving memories. What the automaton's mind did was duplicate relevant memories into smaller memory spaces that it didn't have to search in so widely and deeply. This tactic usually worked pretty well. The automaton was a great partner in casual conversation because of the tactic. However, in instances like this one, the tactic did not work pretty well.

The mind wildly searched memories deeply hidden away, inserting and evicting memories into and from the smaller memory spaces seemingly at random. All the while the automaton sat quietly, not calling out to the old friend by her old nickname. The automaton looked around, saw the faces of friends who'd surely heard what transpired.

"Do they remember?"

The mind made the automaton live through when the old friend received her old nickname. The automaton had given it to her, had picked a nickname for someone else then picked /the/ nickname for her. For whatever reason, it made sense at the time, picking a nickname. The nickname for someone else never stuck. It was the same as a musical artist. The nickname for her was of the same type, a musical artist's. Hers stick.

In the context, the name of the musical artist was also an alteration of an ethnic slur. Without the context, the musical artist's name was just a name. It was her ethnicity that made the nickname stick. The automaton wondered if the mind made a connection between the name and the slur, wondered if it was correct to believe the whole thing was an unfortunate accident or not. What could be said for certain was that the mind knew both words because of the Interconnection.

In any case, it didn't matter. The automaton nicknamed her an ethnic slur. She lived with that slur for years, moved to a different school, and now refused to live with it any longer. 

"I feel bad."

Around the automaton, the party went on. People continued chattering. It was like nobody noticed what had transpired. Or, like the old friend, they were ignoring what the automaton said.

-----

The automaton once listened to two friends arguing. The automaton was in the back seat of a car; the two friends were in the front, one driving on the left, one on the right. The friend on the right, arguing, in the middle of his point, seemingly forgot what he was saying to accuse the automaton of being quiet. He then accused the automaton usually going quiet.

The friend on the right put his hand on his face, said behind his hand that he shouldn't have said that. He remembered that in a different conversation the friend on the left said that that's just the automaton, something that happens because of personality.

It was true. The automaton's felicity was fleeting. It operated like a component on a circuit board, easily shut down with the flick of a switch, or easily slowed by a program's kernel allocating resources toward other components on the system.

The friend on the left continued the argument like they'd never been talking about the automaton. In the backseat, the automaton remained quiet, inserted and evicted memories into and from smaller memory spaces seemingly at random, looked for a human way to feel in this instance.

-----

At the party, the automaton remained quiet. The automaton didn't make conversation with anyone for the remainder of the party. The automaton was too busy looking through all the things the mind stuck into smaller memory spaces.

It gave the automaton all the embarrassing moments texting the old friend. They were both new to texting. The whole world was since cell phones were new to this very generation. The extent of the relationship they'd formed texting was this: It started and ended with calling each other good-looking, in their own unique ways, with an endearing pet name, via text. This was just about how all the potentially romantic relationships of the child automaton went.

The automaton's experience was in contract to the rest of the world who'd made a ruckus about cell phones ushering in a whole new mode of apparent promiscuity. The rest of the world, using the dominant content platforms, popularized the term "sexting." To sext means to send naked photos of onself. It is also an ecclesiastical word for a kind of service. One would think according to what one heard on the Interconnection that /all/ the kids were sexting.

It was a strange world to live in, because the financial success of cell phone creators dependend on the dominant content platforms advertising their products in a good light. If people thought cell phones were bad for some reason, it would hurt their bottom line. So cell phone companies worked diligently to market their products on the Interconnection well.

Thankfully for the companies, Americans thought that everything American celebrities did was good. The companies leveraged the fact by putting American celebrities on Interconnection tabloids. They did it by apparently forgetting to store these celebrities' sexts securely. Hackers found the intimate photographs and leaked them to everyone.

This happened again and again, and eventually the whole world thought sexting wasn't just something that kids were doing. It couldn't be true if so many American celebrities were doing it too. They even thought that maybe they themselves could do it.

This led to many niche emerging market opportunities. Because not everyone had someone to sext, companies formed with the intent to exploit them. They marketed their product as connecting individuals, for only a nominal fee.

As peoples' sexual fantasies became commodified, eventually so too were their ordinary relationships. The niche became the regular. The embarrassing moments the automaton had with the old friend were eventually made a fact of life. The Interconnection became a host for dating. Finding someone who might want to hear a unique way to be called good-looking was relegated to one of the many dating suites.

It would seem plausible that dating could still be done the old fashioned way, however, the number of people having sex dropped significantly since the commodification of relationiships by Interconnection companies. For people like the automaton, who didn't have good understanding of real, human connections, using the designated market seemed the approriate thing to do (humiliating as it was).

In a contemplative state at the party, thinking of ethnic slurs and embarrassing tries at dating, the automaton became depressed. The automaton didn't want to be derisive nor unsociable. The automaton wondered if this was a human way to feel or not.

"I feel bad."

As the Interconnection matured with time, longitudinal studies found that it made people feel depressed. It was particularly true for people who'd used the Interconnection habitually. Interconnection companies believed in the converse, that depressed people often habitually used their products.

As the automaton matured with time, the Plan gained clarity of purpose. .

* TODO Guns and Bombs

When an individual was apprehended by the authorities, on a dreary morning in March, it was because the automaton failed to follow through on the Plan. The Individual wanted to make an impact on the world. It was the kind of impact that went against the Plan.

The automaton found the Individual on the Interconnection. From what could be gleaned from the evidence, extrapolated from psychology, the automaton found the Individual was creating a bomb that he was going to use to kill people.

The automaton was working dilligently to stop the Individual from killing people. The automaton was creating content on the Interconnection, distributing it to the places the Individual habited, where the Individual could use it as a lens to see the error of his ways. The automaton worked quickly, because state authorities were also working to stop the Individual.

Before the Individual was apprehended, a few years ago when he had disposable income and time on his hands, he wanted to purchase a gun that he could fire at the shooting range. This particular spending habit was decided in part by his own father's. His father purchased a gun for protection. His father witnessed a recent series of protests and riots on the news, and thought it would be necessary to have a gun in case the unrest spread to his own city.

The unrest happened two-hundred-sixty-five miles away from the Individual's father, and didn't spread. The unrest didn't see anyone die, though it started because of one death: A man was shot by a police officer.

Along with the .

* TODO Trax

I was a Traxene. Alongside me, the automaton. I was explaining to the strange creature what my world was like. As I talked, the strange creature's face looked more and more familiar.

I explained the ways of Dole Trax bloodletting. Just like my teachers, I emphasized that it didn't have much to do with blood. Despite the name, it was a different fluid of the same color. Just like my teachers, I told the lie that the practice was to combat hydrocephalus. I told the automaton drinking the excess fluid from the head of our Dole brothers was therapeutic and spiritual. I told the automaton the lie that it was a kind thing to do.

"Why do you drink it?"

It was amazing to see the alien take so quickly to Trax.

"We can all glue wings to our sandals."

The way a Traxene feels on Dole Trax cerebrospinal fluid is near indescribable. The automaton wanted to try it, but I told the creature it wouldn't feel near the same. It was the feeling that made the practice make sense. It was otherwise wretched cannibalism.

"But I've come from so far away."

The automaton didn't look so much like a creature anymore. Maybe I just forgot what the creature's face looked like before. The automaton almost looked familiar.

I said it could be done. I myself had been starting to have cravings. I said it could not be done easily. Though the Dole kind were precious, so was their fluid. Since the establishment of the monarchies, the fluid had become scarce. I told the automaton I had no proprietorship, no wealth to host a banquet for even just two. But I could promise the creature a taste.

At that moment, I thought the automaton might have looked just like me. I stepped away from thought so my vision could focus. The automaton looked like the creature did before. Though maybe I'm remember wrong.

"Who are the monarchs?"

When foreign Trax sunk the Dole homeland, Dole Traxene were forced into exile. A new, disillusioned generation emerged from the homes of these exiles. They saw clearly how the foreigners destroyed their homeland. With their forced integration into foreign Trax society, they saw the economic advantage their anatomy gave them.

In their homeland they were treated like cattle, the foreigners milked them for their fluids. The foreigners extracted their land's natural resources, which caused their cities to sink. Chasing freedom, Doles blended in with foreign Trax life. A Dole looked no different from any foreign Trax.

They milked themselves in secret and sold their fluids in open markets. Initially they survived. The disillusioned generation realized their worth. They found humane methods to derive their fluid. They became rich.

In the fabric of Trax society they established feudal-like systems. Foreign Trax would promise protection to Doles in exchange for Dole fluid. These systems of protection grew to support large families of Dole Trax. In time, they established an unrivaled peerage. They took state powers. They became monarchs.

* TODO A Filipino Story

Its success stems from its ability to define the language of debate in a given area. Like for example in the Phillipines when it pitted citizens in the countryside against those of urban areas. The language of countryside debaters focused on criminal drug abuse and the evils of communism. While the language of the urban debaters focused on how journalists were being disappeared in the night.

The way it defined these oppositional outlooks was by letting the country's military personnel make hundreds of accounts to spout their beliefs on drug abuse and the evils of communism with. It would then take money from the country's politicians to distribute those beliefs throughout the platform for more people to see.

It would limit the distribution to just enough Connected people in the countryside to where there would be a majority of people who saw a need to go to war against drug-use and communism. They would elect politicians with just that platform. Those politicians would then work to make anyone disappear who was not in line with that party platform. The Connected people who noticed, were those in urban areas who'd seen that the country's dissenters suddenly vanished.
